/** Download a universal APK generated by Play, and verify its identity before exposing it. */
import { execFileSync } from 'node:child_process'
import { writeFileSync, renameSync, rmSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import { getPlayAccessToken, playRequest, readPlayServiceAccount } from './play-api.mjs'

export const PLAY_PACKAGE = 'ca.dynamicsolutions.sonarbridge'

/** Normalize the colon-separated Console fingerprint and Play's plain SHA-256 form. */
export function normalizeCertificate(value) {
  const normalized = String(value).replace(/:/g, '').toLowerCase()
  if (!/^[0-9a-f]{64}$/.test(normalized)) throw new Error('Invalid signing certificate SHA-256 fingerprint.')
  return normalized
}

/** Require the app-signing fingerprint from Play Console, independently of API download metadata. */
export function trustedPlayCertificates(fingerprint) {
  if (!fingerprint) throw new Error('PLAY_SIGNING_CERTIFICATE_SHA256 is not set. Use the app-signing certificate, not the upload key.')
  return new Set([normalizeCertificate(fingerprint)])
}

/** Return the sole trusted universal APK; missing artifacts can be retried while Play generates them. */
export function selectUniversalApk(metadata, trusted) {
  const candidates = (metadata.generatedApks ?? []).filter((entry) => entry.generatedUniversalApk?.downloadId)
  for (const entry of candidates) {
    if (!trusted.has(normalizeCertificate(entry.certificateSha256Hash))) {
      throw new Error('Play returned a universal APK signed by an unregistered certificate.')
    }
  }
  if (candidates.length > 1) throw new Error('Multiple universal APK signing identities; choose the intended certificate before publishing.')
  return candidates[0] ?? null
}

/** Check SDK inspection output, including the actual cryptographic signer, against the intended release. */
export function verifyApkIdentity(badging, signing, expected) {
  const identity = /package: name='([^']+)' versionCode='([^']+)' versionName='([^']+)'/.exec(badging)
  if (!identity || identity[1] !== PLAY_PACKAGE || identity[2] !== String(expected.code) || identity[3] !== expected.version) {
    throw new Error('Downloaded APK package or version does not match the requested Play release.')
  }
  const fingerprints = [...signing.matchAll(/Signer #\d+ certificate SHA-256 digest:\s*([a-fA-F0-9:]+)/g)]
  if (fingerprints.length !== 1 || normalizeCertificate(fingerprints[0][1]) !== normalizeCertificate(expected.certificate)) {
    throw new Error('Downloaded APK signer does not match the trusted Play signing certificate.')
  }
}

/** Poll only generation delays, then download once. Authentication and trust failures fail immediately. */
export async function downloadPlayApk({ token, code, trusted, api = 'https://androidpublisher.googleapis.com', fetchRequest = playRequest, sleep = (ms) => new Promise((done) => setTimeout(done, ms)), attempts = 21 }) {
  const base = `${api}/androidpublisher/v3/applications/${PLAY_PACKAGE}/generatedApks/${code}`
  const request = (url) => fetchRequest(url, {
    headers: { Authorization: `Bearer ${token}` },
    signal: AbortSignal.timeout(60_000)
  }, 'Google Play generated APKs')
  let selected
  for (let attempt = 0; attempt < attempts; attempt++) {
    const response = await request(base)
    if (!response.ok && response.status !== 404) throw new Error(`Could not list Play APKs (HTTP ${response.status}).`)
    selected = response.ok ? selectUniversalApk(await response.json(), trusted) : null
    if (selected) break
    if (attempt + 1 < attempts) await sleep(30_000)
  }
  if (!selected) throw new Error('Play has not generated a trusted universal APK. Retry later; no direct APK will be published.')
  const downloadId = encodeURIComponent(selected.generatedUniversalApk.downloadId)
  const response = await request(`${base}/downloads/${downloadId}:download?alt=media`)
  if (!response.ok) throw new Error(`Could not download Play APK (HTTP ${response.status}).`)
  return { bytes: Buffer.from(await response.arrayBuffer()), certificate: selected.certificateSha256Hash }
}

/** Keep unverified bytes under a temporary name and remove them on every failure. */
async function main() {
  const { values } = parseArgs({ options: {
    'version-code': { type: 'string' },
    version: { type: 'string' },
    output: { type: 'string' }
  } })
  if (!/^[1-9]\d*$/.test(values['version-code'] ?? '') || !/^\d+\.\d+\.\d+$/.test(values.version ?? '') || !values.output) {
    throw new Error('Usage: play-apk.mjs --version-code NUMBER --version X.Y.Z --output FILE')
  }
  const trusted = trustedPlayCertificates(process.env.PLAY_SIGNING_CERTIFICATE_SHA256)
  const token = await getPlayAccessToken(readPlayServiceAccount(process.env.PLAY_SERVICE_ACCOUNT_JSON))
  const downloaded = await downloadPlayApk({ token, code: values['version-code'], trusted })
  const temporary = `${values.output}.unverified`
  try {
    writeFileSync(temporary, downloaded.bytes, { flag: 'wx' })
    const badging = execFileSync(process.env.AAPT || 'aapt', ['dump', 'badging', temporary], { encoding: 'utf8' })
    const signing = execFileSync(process.env.APKSIGNER || 'apksigner', ['verify', '--print-certs', temporary], { encoding: 'utf8' })
    verifyApkIdentity(badging, signing, { code: values['version-code'], version: values.version, certificate: downloaded.certificate })
    renameSync(temporary, values.output)
    console.log(`Verified ${PLAY_PACKAGE} ${values.version} (versionCode ${values['version-code']}), Google Play signer ${normalizeCertificate(downloaded.certificate)}.`)
  } finally {
    rmSync(temporary, { force: true })
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message)
    process.exitCode = 1
  })
}
